# Generated by Django 5.1.4 on 2025-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_typechanges_userchanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchanges',
            name='description',
            field=models.CharField(),
        ),
    ]
