# Generated by Django 5.1.5 on 2025-01-23 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_groupsubprofiles_image_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='PermissionsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.permissions')),
            ],
            options={
                'verbose_name': 'GroupPermission',
                'verbose_name_plural': 'GroupPermissions',
            },
        ),
        migrations.CreateModel(
            name='SubprofilesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_group.jpg', upload_to='profile_images')),
                ('permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.permissionsgroup')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
                ('subprofile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.subprofile')),
            ],
            options={
                'verbose_name': 'GroupSubprofile',
                'verbose_name_plural': 'GroupSubprofiles',
            },
        ),
        migrations.DeleteModel(
            name='GroupSubprofiles',
        ),
        migrations.AddIndex(
            model_name='permissionsgroup',
            index=models.Index(fields=['id', 'permissions_id'], name='permissions_group_idx'),
        ),
        migrations.AddIndex(
            model_name='subprofilesgroup',
            index=models.Index(fields=['id', 'subprofile_id'], name='subprofile_group_idx'),
        ),
    ]
