# Generated by Django 5.1.5 on 2025-01-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_permissions_permissionsgroup_subprofilesgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprofile',
            name='name',
        ),
    ]
