# Generated by Django 5.1.5 on 2025-01-28 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_subprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='subprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='subprofile',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subprofile',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
        ),
        migrations.AddField(
            model_name='subprofile',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='subprofile',
            index=models.Index(fields=['profile_id', 'username'], name='profile_subprofile_idx'),
        ),
    ]
