# Generated by Django 5.1.4 on 2025-03-24 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_userchanges_main_user_userchanges_user_changed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchanges',
            options={'verbose_name': 'UserChange', 'verbose_name_plural': 'UserChanges'},
        ),
        migrations.CreateModel(
            name='GroupChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('group_changed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_changed_group', to=settings.AUTH_USER_MODEL)),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user_group', to=settings.AUTH_USER_MODEL)),
                ('type_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.typechanges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GroupChange',
                'verbose_name_plural': 'GroupChanges',
            },
        ),
    ]
