# Generated by Django 5.1.5 on 2025-01-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_subprofile_user_subprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='subprofile',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subprofile',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
        ),
        migrations.AlterField(
            model_name='subprofile',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
