# Generated by Django 5.1.5 on 2025-03-26 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_userchanges_options_groupchanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchanges',
            name='group_changed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_changed_group', to='Users.subprofilesgroup'),
        ),
    ]
