# Generated by Django 5.1.4 on 2025-02-24 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_subprofile_email_alter_subprofile_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subprofilesgroup',
            name='subprofile_group_idx',
        ),
        migrations.RemoveField(
            model_name='subprofilesgroup',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='subprofilesgroup',
            name='subprofile_id',
        ),
        migrations.AddField(
            model_name='subprofile',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.subprofilesgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subprofilesgroup',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
