# Generated by Django 5.1.4 on 2025-04-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_groupchanges_group_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprofilesgroup',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='groupchanges',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userchanges',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
