# Generated by Django 5.1.4 on 2025-02-26 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_subprofilesgroup_subprofile_group_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprofilesgroup',
            name='user_id',
        ),
        migrations.AddField(
            model_name='subprofilesgroup',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
            preserve_default=False,
        ),
    ]
