# Generated by Django 5.1.4 on 2025-02-26 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_subprofilesgroup_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subprofile',
            name='profile_subprofile_idx',
        ),
        migrations.RemoveField(
            model_name='subprofile',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='subprofilesgroup',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='subprofile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subprofilesgroup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='subprofile',
            index=models.Index(fields=['user', 'username'], name='profile_subprofile_idx'),
        ),
    ]
