# Generated by Django 5.1.4 on 2025-03-04 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_remove_subprofile_profile_subprofile_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subprofile',
            name='profile_subprofile_idx',
        ),
        migrations.RemoveField(
            model_name='subprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='subprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='subprofilesgroup',
            name='user',
        ),
        migrations.AddField(
            model_name='subprofile',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subprofilesgroup',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
            preserve_default=False,
        ),
    ]
