# Generated by Django 5.1.5 on 2025-03-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_subprofile_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='permissionsgroup',
            name='permissions_group_idx',
        ),
        migrations.AddField(
            model_name='permissionsgroup',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissionsgroup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='permissionsgroup',
            name='permissions_id',
        ),
        migrations.AddField(
            model_name='permissionsgroup',
            name='permissions_id',
            field=models.ManyToManyField(related_name='permissions', to='Users.permissions'),
        ),
    ]
