# Imagen base
FROM python:3.11

# Directorio dentro del contenedor
WORKDIR /app

# Copiamos los archivos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Recopila los archivos estáticos durante la construcción de la imagen
RUN python manage.py collectstatic --noinput

# Exponemos el puerto para Django
EXPOSE 8000

# Comando para iniciar el servidor ASGI
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "LogInventory.asgi:application"]
 