# Generated by Django 5.2.3 on 2025-09-26 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Objects', '0009_delete_borrowings'),
        ('Users', '0008_alter_subprofilesgroup_image_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateTimeField(auto_now_add=True)),
                ('date_limit', models.DateTimeField()),
                ('date_complete', models.DateTimeField()),
                ('stock', models.IntegerField()),
                ('in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.subprofile')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Objects.objects')),
            ],
            options={
                'verbose_name': 'Borrowing',
                'verbose_name_plural': 'Borrowings',
            },
        ),
    ]
