# Generated by Django 5.2.5 on 2025-09-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowings',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
