# Generated by Django 5.2.3 on 2025-09-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrowings', '0002_borrowings_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowings',
            name='date_complete',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
