# Generated by Django 5.2.3 on 2025-10-06 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Borrowings", "0003_alter_borrowings_date_complete"),
        ("Objects", "0009_delete_borrowings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowings",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings",
                to="Objects.objects",
            ),
        ),
    ]
