# Generated by Django 5.1.4 on 2025-03-23 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TypeTransaction',
                'verbose_name_plural': 'TypeTransactions',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='objects_images')),
                ('description', models.TextField()),
                ('in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.subprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Objects',
            },
        ),
        migrations.CreateModel(
            name='Borrowings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateTimeField(auto_now_add=True)),
                ('date_limit', models.DateTimeField()),
                ('date_complete', models.DateTimeField()),
                ('stock', models.IntegerField()),
                ('in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.subprofile')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Objects.object')),
            ],
            options={
                'verbose_name': 'Borrowing',
                'verbose_name_plural': 'Borrowings',
            },
        ),
        migrations.CreateModel(
            name='ObjectsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_group.jpg', upload_to='objects_images')),
                ('in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.subprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Objects.objectsgroup'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.subprofile')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Objects.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Objects.typetransaction')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
