# Generated by Django 5.2.3 on 2025-08-23 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0001_initial'),
        ('Users', '0008_alter_subprofilesgroup_image_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupObjectsChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('group_changed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Objects.objectsgroup')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_objects_main_user', to=settings.AUTH_USER_MODEL)),
                ('type_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.typechanges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_objects_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
