# Generated by Django 5.0.6 on 2024-12-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='default_group.jpg', upload_to='objects_images'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='objects_images'),
        ),
    ]
