# Generated by Django 5.2.3 on 2025-08-23 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0002_groupobjectschanges'),
        ('Users', '0008_alter_subprofilesgroup_image_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsgroup',
            name='image',
            field=models.ImageField(default='default_object_group.jpg', upload_to='objects_images'),
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(default='default_object.jpg', upload_to='objects_images')),
                ('description', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Objects.objectsgroup')),
                ('in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.subprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Objects',
            },
        ),
        migrations.AlterField(
            model_name='borrowings',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Objects.objects'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Objects.objects'),
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
