# Generated by Django 5.1.5 on 2025-01-23 02:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0002_alter_group_image_alter_object_image'),
        ('Users', '0003_permissions_permissionsgroup_subprofilesgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ObjectsGroup',
        ),
    ]
