# Generated by Django 5.2.3 on 2025-08-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0003_alter_objectsgroup_image_objects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsgroup',
            name='image',
            field=models.ImageField(default='default_object_group.jpg', upload_to='objectGroups_images'),
        ),
    ]
