# Generated by Django 5.1.5 on 2025-01-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0003_rename_group_objectsgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
