# Generated by Django 5.2.3 on 2025-08-23 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0004_alter_objectsgroup_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects_in_charge', to=settings.AUTH_USER_MODEL),
        ),
    ]
