# Generated by Django 5.2.3 on 2025-09-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0005_alter_transaction_in_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Objects.objectsgroup'),
        ),
    ]
