# Generated by Django 5.2.3 on 2025-09-22 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0006_alter_objects_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Objects.objectsgroup'),
            preserve_default=False,
        ),
    ]
