# Generated by Django 5.2.5 on 2025-09-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0007_alter_objects_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsgroup',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
