# Generated by Django 5.2.3 on 2025-09-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0008_objectsgroup_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrowings',
        ),
    ]
