# Generated by Django 5.2.3 on 2025-10-06 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LiveChats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livechat",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livechat",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="livechat",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
